name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::389233637717:role/vandodevpipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "terraformstatefilebucketvandodev"
      aws-lock-dynamodb-table: "terraformsDynamoDBvandodev"